In [31]:
import tensorflow as tf
print(tf.__version__)

physical_devices = tf.config.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(physical_devices[0], True)

2.4.1


[]

In [18]:
# Initialization of Tensors
x = tf.constant(5, shape=(1,1), dtype=tf.float32)
print(x)

x = tf.constant([[1, 2, 3], [4, 5, 6]])
print(x)

x = tf.ones((3, 3))
print(x)

x = tf.zeros((3, 2))
print(x)

x = tf.eye(4)
print(x)

x = tf.random.normal((3, 3, 4), mean = 0, stddev=1)
print(x)

x = tf.random.uniform((2, 3, 1), minval=0, maxval=1)
print(x)

x = tf.range(start=12, limit=50, delta=5)
print(x)

x = tf.cast(x, dtype=tf.float64)
print(x)

tf.Tensor([[5.]], shape=(1, 1), dtype=float32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]], shape=(4, 4), dtype=float32)
tf.Tensor(
[[[ 0.55486727  1.3722117  -0.08234406 -1.0821774 ]
  [-0.03905461 -0.95766586 -0.6588953  -0.34808645]
  [-0.60673577 -0.18944438 -1.2782978  -0.5253984 ]]

 [[ 0.10839629 -0.07812683 -1.7072905   2.2144344 ]
  [-1.5568018   1.8935933   0.23394819  1.0081271 ]
  [-1.2977152   0.4342687   0.17600217  1.5406469 ]]

 [[-0.36695272  1.1264651   1.7151977   0.4804039 ]
  [-0.593934   -0.90994954 -0.69948727  0.6817447 ]
  [ 1.0112143  -1.0109978   1.007972    0.8113785 ]]], shape=(3, 3, 4), dtype=float32)
tf.Tensor(
[[[0.29448295]
  [0.4797789 ]
  [0.04334593]]

 [[0.8308873 ]
  [0.769277  ]
  [0.81379616]]], shape=(2, 3, 1), dtype

In [32]:
# Mathematical Operations
x = tf.constant([2, 3, 4])
y = tf.constant([8, 9, 10])
z = tf.add(x, y)
print(z)

z = tf.subtract(x, y)
print(z)

z = tf.divide(x, y)
print(z)

z = tf.multiply(x, y)
print(z)

z = tf.tensordot(x, y, axes=1) # Same as tf.reduce_sum(x, y, axis=0)
print(z)

z = x**5
print(z)

x = tf.random.normal((3, 4))
y = tf.random.normal((4, 5))
z = tf.matmul(x, y)
print(z)

tf.Tensor([10 12 14], shape=(3,), dtype=int32)
tf.Tensor([-6 -6 -6], shape=(3,), dtype=int32)
tf.Tensor([0.25       0.33333333 0.4       ], shape=(3,), dtype=float64)
tf.Tensor([16 27 40], shape=(3,), dtype=int32)
tf.Tensor(83, shape=(), dtype=int32)
tf.Tensor([  32  243 1024], shape=(3,), dtype=int32)
tf.Tensor(
[[-2.474565   -0.3389429  -6.530881   -3.1911995   2.5414417 ]
 [-1.3457947   0.58218473 -7.1543     -3.825325    2.0030847 ]
 [-1.0633892   0.5783026   0.78946936  2.3478193  -0.9811282 ]], shape=(3, 5), dtype=float32)


In [42]:
# Indexing
x = tf.constant([[3, 5, 2, 6, 1, 8, 0], [5, 2, 7, 0, 3, 6, 8]])
print(x[:])

print(x[:, 1:])

print(x[::-1])

indices = tf.constant([0, 1])
x_ind = tf.gather(x, indices)

x = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])
print(x[0:2,:])

tf.Tensor(
[[3 5 2 6 1 8 0]
 [5 2 7 0 3 6 8]], shape=(2, 7), dtype=int32)
tf.Tensor(
[[5 2 6 1 8 0]
 [2 7 0 3 6 8]], shape=(2, 6), dtype=int32)
tf.Tensor(
[[5 2 7 0 3 6 8]
 [3 5 2 6 1 8 0]], shape=(2, 7), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [45]:
# Reshaping
x = tf.range(9)
print(x)

x = tf.reshape(x, (3, 3))
print(x)

x = tf.transpose(x, perm=[1,0])
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
